name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Enable Corepack
        shell: bash
        run: |
          node --version
          corepack --version
          corepack enable
          corepack yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn vitest run

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # # Authenticate npm using the OIDC token before publishing
      # - name: Authenticate with npm OIDC
      #   run: |
      #     npm config set //registry.npmjs.org/:_authToken=""
      #     # This forces npm to fetch a token from the ambient OIDC environment
      #     npm login --no-login.web --auth-type=oidc

      # - name: Publish to npm
      #   run: npm publish --provenance --access public

      - name: Create GitHub Release
        run: gh release create ${{ github.ref_name }} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
